remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: axiom4's homepage
description: I'm an Information Technology Enthusiast. I spend my free time searching for sublime solutions to complex problems.
markdown: GFM
